import Link from "next/link";

export const metadata = { title: "Privacy Policy · Allora" };

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-4 py-14 space-y-10">

        <div className="space-y-2">
          <Link href="/dashboard" className="text-xs text-brand-primary hover:underline">← Back to Allora</Link>
          <h1 className="text-3xl font-extrabold text-gray-900 tracking-tight">Privacy Policy</h1>
          <p className="text-sm text-gray-400">Last updated: May 2026</p>
        </div>

        {[
          {
            title: "1. Information we collect",
            body: `We collect information you provide directly — such as your name, email address, and phone number when you register — as well as information generated by your use of Allora, including your device's GPS coordinates (used solely to match you with nearby heroes), booking history, and ratings you leave for heroes.`,
          },
          {
            title: "2. How we use your information",
            body: `Your location is used only to determine which verified heroes serve your area. We do not sell your location data to third parties. Email is used for authentication (OTP) and transactional notifications. Booking data is used to process service requests and facilitate payments.`,
          },
          {
            title: "3. Data sharing",
            body: `We share your name and contact details with the hero you book, solely to fulfil your service request. We engage payment processors (Razorpay, PhonePe) who handle transaction data under their own privacy policies. We do not sell personal data to advertisers.`,
          },
          {
            title: "4. Data retention",
            body: `We retain your account data as long as your account is active. Booking records are retained for seven years for accounting and dispute resolution purposes. You may request deletion of your account and personal data by emailing hello@allora.app.`,
          },
          {
            title: "5. Security",
            body: `We use industry-standard encryption (TLS) for all data in transit. Passwords are never stored — authentication uses one-time email codes only. Sensitive credentials are stored in environment variables and never committed to source control.`,
          },
          {
            title: "6. Your rights",
            body: `You have the right to access, correct, or delete your personal data. To exercise these rights, contact us at hello@allora.app. We will respond within 30 days.`,
          },
          {
            title: "7. Changes to this policy",
            body: `We may update this policy from time to time. Significant changes will be notified via email. Continued use of Allora after such notice constitutes acceptance.`,
          },
          {
            title: "8. Contact",
            body: `Privacy inquiries: hello@allora.app`,
          },
        ].map(({ title, body }) => (
          <section key={title} className="space-y-2">
            <h2 className="font-bold text-gray-900">{title}</h2>
            <p className="text-sm text-gray-600 leading-relaxed">{body}</p>
          </section>
        ))}

        <div className="pt-6 border-t border-gray-100 flex gap-4 text-xs text-gray-400">
          <Link href="/legal/terms" className="hover:text-brand-primary">Terms of Service</Link>
          <Link href="/legal/refund" className="hover:text-brand-primary">Refund Policy</Link>
        </div>
      </div>
    </main>
  );
}
